Improved error parsing when using verilator
mshr-h/vscode-verilog-hdl-support pull request #491
Opened 2024-07-24 12:36 UTC by alex-the-new-guy

Fixed/improved problem matcher regex, added support for parsing a whole project (theoretically) instead of current file only. Guess that's it.

2024-07-25 12:35 UTC, mshr-h commented
Thanks! I'll review it in a few days.

2024-07-27 05:02 UTC, mshr-h requested changes

2024-07-27 08:25 UTC, alex-the-new-guy commented on src/linter/VerilatorLinter.ts
> +            rex[5] = rex[5].replace(/(\\\\)|(\\)/, "/");
The error was  the lack of `global` tag in the end. Fixed.

2024-07-27 08:29 UTC, alex-the-new-guy commented on src/linter/VerilatorLinter.ts
> +        this.logger.info(`[verilator] ${error_warning_counter} errors/warnings returned`);
After it's done, Verilator prints something like `%Error: Exiting due to 3 error(s) and 2 warning(s)`, which is passed through to the user (well, console). This message is redundant and less informative, thus has been removed entirely.

2024-07-27 08:29 UTC, alex-the-new-guy commented on src/linter/VerilatorLinter.ts
> +        let filesDiag = {};
Fixed

2024-07-27 08:30 UTC, alex-the-new-guy commented on src/linter/VerilatorLinter.ts
> +        let error_warning_counter = 0;
Fixed

2024-07-27 08:30 UTC, alex-the-new-guy commented on src/linter/VerilatorLinter.ts
> +        //let diagnostics: vscode.Diagnostic[] = [];
Fixed

2024-07-28 00:20 UTC, alex-the-new-guy commented
When / if you look at this, have a look at this, have a look at precise_highlight branch
I've added highlighting based on Verilator-provided messages and parsing for additional messages that elaborate the issue. 

It's not production-quality code yet and the whole thing turned into a bit of a mess, but main functionality is there.

2024-07-30 12:43 UTC, merged

2024-07-30 12:43 UTC, mshr-h commented
@alex-the-new-guy LGTM. Thanks!
I'll also check your email later.

2025-02-04 05:16 UTC, zoomer-k commented
@mshr-h 
#512 
this commit contain problem for windows 
could you rollback ?

2026-01-06 05:52 UTC, zoomer-k commented
@mshr-h 
remention
https://github.com/mshr-h/vscode-verilog-hdl-support/issues/512